debug: false

server:
  port: ${port:8080}
  tomcat:
    max-connections: 16384
    max-threads: 768

spring:
  application:
    name: samples-aws-dynamodb
  jmx:
    enabled: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

amazon:
  aws:
    access-key-id: ENC(618850677489B456E0C901097F6E0B9CF273C45D56628E105EF043A60D2C4CE9)
    access-key-secret: ENC(33013FEDD886E3C78E8727E78F2B097AE58180F568AE81854A4386BC815B27B2B5785F4D557FE2F9ACF632ECC465985BEA7192B6BAD9F022)
    dynamodb:
      reason: eu-west-1

logging:
  config: classpath:logback.xml
